# table with instruction blueprints
#
# instruction name:   ['pre-run cpu method', {instruction kwargs}, 'post-run memory method']

INSTRUCTION_TABLE = {

    # single instructions
    'special':                  ['', {}],
    'direct_read8':             ['', {'m': 'get_m_direct'}],
    'direct_A_read8':           ['', {'m': 'get_m_direct', 'register': 'accu_a'}],
    'direct_B_read8':           ['', {'m': 'get_m_direct', 'register': 'accu_b'}],
    'direct_ea':                ['', {'ea': 'get_ea_direct'}],
    'direct_word_D_read16':     ['', {'m': 'get_m_direct_word', 'register': 'accu_d'}],
    'direct_word_S_read16':     ['', {'m': 'get_m_direct_word', 'register': 'system_stack_pointer'}],
    'direct_word_U_read16':     ['', {'m': 'get_m_direct_word', 'register': 'user_stack_pointer'}],
    'direct_word_X_read16':     ['', {'m': 'get_m_direct_word', 'register': 'index_x'}],
    'direct_word_Y_read16':     ['', {'m': 'get_m_direct_word', 'register': 'index_y'}],
    'extended_read8':           ['', {'m': 'get_m_extended'}],
    'extended_A_read8':         ['', {'m': 'get_m_extended', 'register': 'accu_a'}],
    'extended_B_read8':         ['', {'m': 'get_m_extended', 'register': 'accu_b'}],
    'extended_ea':              ['', {'ea': 'get_ea_extended'}],
    'extended_word_D_read16':   ['', {'m': 'get_m_extended_word', 'register': 'accu_d'}],
    'extended_word_S_read16':   ['', {'m': 'get_m_extended_word', 'register': 'system_stack_pointer'}],
    'extended_word_U_read16':   ['', {'m': 'get_m_extended_word', 'register': 'user_stack_pointer'}],
    'extended_word_X_read16':   ['', {'m': 'get_m_extended_word', 'register': 'index_x'}],
    'extended_word_Y_read16':   ['', {'m': 'get_m_extended_word', 'register': 'index_y'}],
    'immediate_read8':          ['', {'m': 'get_m_immediate'}],
    'immediate_A_read8':        ['', {'m': 'get_m_immediate', 'register': 'accu_a'}],
    'immediate_B_read8':        ['', {'m': 'get_m_immediate', 'register': 'accu_b'}],
    'immediate_CC_read8':       ['', {'m': 'get_m_immediate', 'register': 'cc'}],
    'immediate_S_read8':        ['', {'m': 'get_m_immediate', 'register': 'system_stack_pointer'}],
    'immediate_U_read8':        ['', {'m': 'get_m_immediate', 'register': 'user_stack_pointer'}],
    'immediate_word_D_read16':  ['', {'m': 'get_m_immediate_word', 'register': 'accu_d'}],
    'immediate_word_S_read16':  ['', {'m': 'get_m_immediate_word', 'register': 'system_stack_pointer'}],
    'immediate_word_U_read16':  ['', {'m': 'get_m_immediate_word', 'register': 'user_stack_pointer'}],
    'immediate_word_X_read16':  ['', {'m': 'get_m_immediate_word', 'register': 'index_x'}],
    'immediate_word_Y_read16':  ['', {'m': 'get_m_immediate_word', 'register': 'index_y'}],
    'indexed_read8':            ['', {'m': 'get_m_indexed'}],
    'indexed_A_read8':          ['', {'m': 'get_m_indexed', 'register': 'accu_a'}],
    'indexed_B_read8':          ['', {'m': 'get_m_indexed', 'register': 'accu_b'}],
    'indexed_ea':               ['', {'ea': 'get_ea_indexed'}],
    'indexed_ea_S':             ['', {'ea': 'get_ea_indexed', 'register': 'system_stack_pointer'}],
    'indexed_ea_U':             ['', {'ea': 'get_ea_indexed', 'register': 'user_stack_pointer'}],
    'indexed_ea_X':             ['', {'ea': 'get_ea_indexed', 'register': 'index_x'}],
    'indexed_ea_Y':             ['', {'ea': 'get_ea_indexed', 'register': 'index_y'}],
    'indexed_word_D_read16':    ['', {'m': 'get_m_indexed_word', 'register': 'accu_d'}],
    'indexed_word_S_read16':    ['', {'m': 'get_m_indexed_word', 'register': 'system_stack_pointer'}],
    'indexed_word_U_read16':    ['', {'m': 'get_m_indexed_word', 'register': 'user_stack_pointer'}],
    'indexed_word_X_read16':    ['', {'m': 'get_m_indexed_word', 'register': 'index_x'}],
    'indexed_word_Y_read16':    ['', {'m': 'get_m_indexed_word', 'register': 'index_y'}],
    'inherent':                 ['', {}],
    'inherent_A':               ['', {'register': 'accu_a'}],
    'inherent_B':               ['', {'register': 'accu_b'}],
    'relative_ea':              ['', {'ea': 'get_ea_relative'}],
    'relative_word_ea':         ['', {'ea': 'get_ea_relative_word'}],
    'direct_ea_write8':         ['', {'ea': 'get_ea_direct'}, 'write_byte'],

    # instruction + write
    'direct_ea_A_write8':       ['', {'ea': 'get_ea_direct', 'register': 'accu_a'}, 'write_byte'],
    'direct_ea_B_write8':       ['', {'ea': 'get_ea_direct', 'register': 'accu_b'}, 'write_byte'],
    'direct_ea_D_write16':      ['', {'ea': 'get_ea_direct', 'register': 'accu_d'}, 'write_word'],
    'direct_ea_S_write16':      ['', {'ea': 'get_ea_direct', 'register': 'system_stack_pointer'}, 'write_word'],
    'direct_ea_U_write16':      ['', {'ea': 'get_ea_direct', 'register': 'user_stack_pointer'}, 'write_word'],
    'direct_ea_X_write16':      ['', {'ea': 'get_ea_direct', 'register': 'index_x'}, 'write_word'],
    'direct_ea_Y_write16':      ['', {'ea': 'get_ea_direct', 'register': 'index_y'}, 'write_word'],
    'extended_ea_write8':       ['', {'ea': 'get_ea_extended'}, 'write_byte'],
    'extended_ea_A_write8':     ['', {'ea': 'get_ea_extended', 'register': 'accu_a'}, 'write_byte'],
    'extended_ea_B_write8':     ['', {'ea': 'get_ea_extended', 'register': 'accu_b'}, 'write_byte'],
    'extended_ea_D_write16':    ['', {'ea': 'get_ea_extended', 'register': 'accu_d'}, 'write_word'],
    'extended_ea_S_write16':    ['', {'ea': 'get_ea_extended', 'register': 'system_stack_pointer'}, 'write_word'],
    'extended_ea_U_write16':    ['', {'ea': 'get_ea_extended', 'register': 'user_stack_pointer'}, 'write_word'],
    'extended_ea_X_write16':    ['', {'ea': 'get_ea_extended', 'register': 'index_x'}, 'write_word'],
    'extended_ea_Y_write16':    ['', {'ea': 'get_ea_extended', 'register': 'index_y'}, 'write_word'],
    'indexed_ea_write8':        ['', {'ea': 'get_ea_indexed'}],
    'indexed_ea_A_write8':      ['', {'ea': 'get_ea_indexed', 'register': 'accu_a'}, 'write_byte'],
    'indexed_ea_B_write8':      ['', {'ea': 'get_ea_indexed', 'register': 'accu_b'}, 'write_byte'],
    'indexed_ea_D_write16':     ['', {'ea': 'get_ea_indexed', 'register': 'accu_d'}, 'write_word'],
    'indexed_ea_S_write16':     ['', {'ea': 'get_ea_indexed', 'register': 'system_stack_pointer'}, 'write_word'],
    'indexed_ea_U_write16':     ['', {'ea': 'get_ea_indexed', 'register': 'user_stack_pointer'}, 'write_word'],
    'indexed_ea_X_write16':     ['', {'ea': 'get_ea_indexed', 'register': 'index_x'}, 'write_word'],
    'indexed_ea_Y_write16':     ['', {'ea': 'get_ea_indexed', 'register': 'index_y'}, 'write_word'],

    # action + instruction + write
    'direct_ea_read8_write8':   ['get_ea_m_direct', {}, 'write_byte'],
    'extended_ea_read8_write8': ['get_ea_m_extended', {}, 'write_byte'],
    'indexed_ea_read8_write8':  ['get_ea_m_indexed', {}, 'write_byte'],
}